#!/usr/bin/env python3
"""Evaluate BFPA4->BFPA6 refinement policies from saved activation traces.

This script reuses ``activation_node_trace.tsv`` generated by
``diagnose_graphbfp_activation_stress.py``.  It does not run LLaMA again.  It
loads BFPA8/BFPA4/BFPA6 embedding pools, trains the GNN on BFPA8, then tests
which traced nodes should be lifted from BFPA4 to BFPA6.
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import numpy as np
import torch
import torch.nn.functional as F

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from GraphhopSimhash.data import load_run_state  # noqa: E402
from GraphhopSimhash.real_quant import build_real_quant_scores, default_pool_path, load_tensor_pool  # noqa: E402
from GraphhopSimhash.runner import evaluate_gnn_embeddings, train_baseline_model  # noqa: E402
from GraphhopSimhash.scripts.diagnose_graphbfp_signal_quality import _mean_rows, _normalize  # noqa: E402


def _write_tsv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()), delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)


def _make_run_args(args: argparse.Namespace, seed: int) -> SimpleNamespace:
    return SimpleNamespace(
        llm_name=args.llm_name,
        emb_dim=args.emb_dim,
        radius=args.radius,
        max_test=args.max_test,
        standard_eval_baseline=args.standard_eval_baseline,
        hash_view=args.hash_view,
        hash_mix_weights=args.hash_mix_weights,
        sketch_bits=args.sketch_bits,
        controller_seed=seed,
        run_seed=seed,
        score_rarity_bits=args.score_rarity_bits,
        score_rarity_seed=args.score_rarity_seed,
        score_propagation_weight=args.score_propagation_weight,
        score_graph_context_weight=args.score_graph_context_weight,
        score_low_unique_weight=args.score_low_unique_weight,
    )


def _load_trace(path: Path, n: int, metric: str, device: torch.device) -> tuple[torch.Tensor, torch.Tensor]:
    values = torch.zeros(n, dtype=torch.float32, device=device)
    mask = torch.zeros(n, dtype=torch.bool, device=device)
    with path.open("r", encoding="utf-8") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if metric not in reader.fieldnames:
            raise ValueError(f"{metric} not in {path}; fields={reader.fieldnames}")
        for row in reader:
            node_id = int(row["node_id"])
            if 0 <= node_id < n:
                values[node_id] = float(row[metric])
                mask[node_id] = True
    return values, mask


def _rank_score(score: torch.Tensor, candidate_mask: torch.Tensor | None = None) -> torch.Tensor:
    out = torch.zeros_like(score, dtype=torch.float32)
    if candidate_mask is None:
        candidate_mask = torch.ones(score.numel(), dtype=torch.bool, device=score.device)
    idx = torch.nonzero(candidate_mask, as_tuple=False).flatten()
    if int(idx.numel()) == 0:
        return out
    local = score[idx]
    order = torch.argsort(local, descending=False)
    ranks = torch.empty_like(order, dtype=torch.float32)
    ranks[order] = torch.arange(int(order.numel()), dtype=torch.float32, device=score.device)
    denom = max(1, int(order.numel()) - 1)
    out[idx] = ranks / float(denom)
    return out


def _make_signals(
    degree: torch.Tensor,
    tser: torch.Tensor,
    act: torch.Tensor,
    trace_mask: torch.Tensor,
    seed: int,
) -> dict[str, torch.Tensor]:
    degree = _normalize(degree)
    tser = _normalize(tser)
    act = _normalize(act)
    gen = torch.Generator(device="cpu")
    gen.manual_seed(int(seed) + 907)
    random = torch.rand(degree.numel(), generator=gen).to(degree.device)

    degree_r = _rank_score(degree, trace_mask)
    tser_r = _rank_score(tser, trace_mask)
    act_r = _rank_score(act, trace_mask)
    eps = 1e-6
    signals = {
        "Random": random,
        "Degree": degree,
        "TSER": tser,
        "ActStress": act,
        "DegreeXAct": degree.clamp_min(eps) * act.clamp_min(eps),
        "TSERXAct": tser.clamp_min(eps) * act.clamp_min(eps),
        "Degree80Act20": 0.8 * degree_r + 0.2 * act_r,
        "Degree50Act50": 0.5 * degree_r + 0.5 * act_r,
        "Degree20Act80": 0.2 * degree_r + 0.8 * act_r,
        "TSER80Act20": 0.8 * tser_r + 0.2 * act_r,
        "TSER50Act50": 0.5 * tser_r + 0.5 * act_r,
        "TSER20Act80": 0.2 * tser_r + 0.8 * act_r,
    }

    # Two-stage policies: graph selects a fragile candidate pool; activation
    # stress ranks inside that pool.  Values outside the candidate pool are low.
    for graph_name, graph_score in (("Degree", degree), ("TSER", tser)):
        for candidate_frac in (0.5, 0.7):
            idx = torch.nonzero(trace_mask, as_tuple=False).flatten()
            k = max(1, int(round(float(candidate_frac) * int(idx.numel()))))
            candidate = torch.zeros_like(trace_mask)
            candidate[idx[torch.argsort(graph_score[idx], descending=True)[:k]]] = True
            local_act_rank = _rank_score(act, candidate)
            signals[f"{graph_name}Top{int(candidate_frac*100)}_Act"] = local_act_rank
    return signals


def _mix_by_score(
    base_hidden: torch.Tensor,
    refine_hidden: torch.Tensor,
    score: torch.Tensor,
    trace_mask: torch.Tensor,
    ratio: float,
) -> tuple[torch.Tensor, torch.Tensor]:
    idx = torch.nonzero(trace_mask, as_tuple=False).flatten()
    k = max(0, min(int(idx.numel()), int(round(float(ratio) * int(idx.numel())))))
    mask = torch.zeros(score.numel(), dtype=torch.bool, device=score.device)
    if k > 0:
        selected = idx[torch.argsort(score[idx], descending=True)[:k]]
        mask[selected] = True
    mixed = base_hidden.clone()
    mixed[mask] = refine_hidden[mask]
    return mixed, mask


def _format(rows: list[dict[str, Any]]) -> str:
    cols = [("ratio", 7), ("best", 18), ("best_drop", 10), ("random", 10), ("degree", 10), ("tser", 10), ("act", 10)]
    lines = [" ".join(name.rjust(w) for name, w in cols)]
    lines.append("-" * len(lines[0]))
    for ratio in sorted({float(r["ratio"]) for r in rows}):
        sub = [r for r in rows if math.isclose(float(r["ratio"]), ratio)]
        by = {r["policy"]: float(r["drop"]) for r in sub}
        best = min(sub, key=lambda r: float(r["drop"]))
        vals = {
            "ratio": f"{ratio:.0%}",
            "best": best["policy"],
            "best_drop": f"{float(best['drop']):.2%}",
            "random": f"{by.get('Random', float('nan')):.2%}",
            "degree": f"{by.get('Degree', float('nan')):.2%}",
            "tser": f"{by.get('TSER', float('nan')):.2%}",
            "act": f"{by.get('ActStress', float('nan')):.2%}",
        }
        lines.append(" ".join(str(vals[name]).rjust(w) for name, w in cols))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", default="cora", choices=["cora", "pubmed", "arxiv"])
    parser.add_argument("--trace_path", required=True)
    parser.add_argument("--activation_metric", default="act_outlier_p90")
    parser.add_argument("--model_name", default="llama2_7b")
    parser.add_argument("--reference_tag", default="W4BFPA8_B128")
    parser.add_argument("--base_tag", default="W4BFPA4_B128")
    parser.add_argument("--refine_tag", default="W4BFPA6_B128")
    parser.add_argument("--ratios", nargs="+", type=float, default=[0.10, 0.20, 0.25, 0.30, 0.40])
    parser.add_argument("--runs", type=int, default=3)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--llm_name", default="ST")
    parser.add_argument("--emb_dim", type=int, default=768)
    parser.add_argument("--radius", type=int, default=2)
    parser.add_argument("--max_test", type=int, default=None)
    parser.add_argument("--standard_eval_baseline", action="store_true")
    parser.add_argument("--hash_view", default="mix")
    parser.add_argument("--hash_mix_weights", nargs=3, type=float, default=[0.30, 0.70, 0.0])
    parser.add_argument("--sketch_bits", type=int, default=14)
    parser.add_argument("--score_rarity_bits", type=int, default=12)
    parser.add_argument("--score_rarity_seed", type=int, default=12345)
    parser.add_argument("--score_propagation_weight", type=float, default=3.0)
    parser.add_argument("--score_graph_context_weight", type=float, default=1.0)
    parser.add_argument("--score_low_unique_weight", type=float, default=1.0)
    parser.add_argument("--output_dir", default=None)
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    out_dir = Path(args.output_dir) if args.output_dir else ROOT / "output" / "graphbfp_activation_policy" / args.dataset
    out_dir.mkdir(parents=True, exist_ok=True)

    ref = load_tensor_pool(default_pool_path(args.dataset, args.model_name, args.reference_tag), device)
    base = load_tensor_pool(default_pool_path(args.dataset, args.model_name, args.base_tag), device)
    refine = load_tensor_pool(default_pool_path(args.dataset, args.model_name, args.refine_tag), device)
    act, trace_mask = _load_trace(Path(args.trace_path), ref.size(0), args.activation_metric, device)
    if int(trace_mask.sum().item()) == 0:
        raise ValueError("trace file contains no valid nodes")

    rows = []
    baseline_accs = []
    base_accs = []
    refine_accs = []
    for run_idx in range(int(args.runs)):
        seed = int(args.seed) + run_idx
        run_args = _make_run_args(args, seed)
        _conf, data, verify_features, run_device = load_run_state(args.dataset, run_args, seed)
        ref_dev = ref.to(run_device)
        base_dev = base.to(run_device)
        refine_dev = refine.to(run_device)
        act_dev = act.to(run_device)
        trace_mask_dev = trace_mask.to(run_device)

        data.x = ref_dev
        model, baseline_acc, _ref_hidden, _ref_logits = train_baseline_model(data, run_args, run_device)
        with torch.no_grad():
            base_hidden = model.encoder(base_dev)
            refine_hidden = model.encoder(refine_dev)
        base_acc = evaluate_gnn_embeddings(model, data, base_hidden)
        refine_acc = evaluate_gnn_embeddings(model, data, refine_hidden)
        baseline_accs.append(float(baseline_acc))
        base_accs.append(float(base_acc))
        refine_accs.append(float(refine_acc))

        scores = build_real_quant_scores(verify_features, data, run_args, run_device)
        signals = _make_signals(
            scores["propagation_q"].to(run_device),
            scores["sensitivity_q"].to(run_device),
            act_dev,
            trace_mask_dev,
            seed,
        )
        for ratio in args.ratios:
            for policy, sig in signals.items():
                mixed_hidden, selected = _mix_by_score(base_hidden, refine_hidden, sig, trace_mask_dev, ratio)
                acc = evaluate_gnn_embeddings(model, data, mixed_hidden)
                rows.append(
                    {
                        "seed": seed,
                        "ratio": float(ratio),
                        "policy": policy,
                        "trace_nodes": int(trace_mask_dev.sum().item()),
                        "refined_nodes": int(selected.sum().item()),
                        "baseline_acc": float(baseline_acc),
                        "base_acc": float(base_acc),
                        "refine_acc": float(refine_acc),
                        "acc": float(acc),
                        "drop": float(baseline_acc - acc),
                        "gain_vs_base": float(acc - base_acc),
                    }
                )

    summary = _mean_rows(
        rows,
        ["trace_nodes", "refined_nodes", "baseline_acc", "base_acc", "refine_acc", "acc", "drop", "gain_vs_base"],
        ["ratio", "policy"],
    )
    _write_tsv(out_dir / "policy_per_seed.tsv", rows)
    _write_tsv(out_dir / "policy_summary.tsv", summary)
    note = "\n".join(
        [
            f"Graph-BFP activation-policy evaluation | dataset={args.dataset} | runs={args.runs}",
            f"trace={args.trace_path}",
            f"trace_nodes={int(trace_mask.sum().item())}",
            f"Baseline Acc: {float(np.mean(baseline_accs)):.4f}",
            f"All {args.base_tag}: Acc={float(np.mean(base_accs)):.4f}, Drop={float(np.mean(np.array(baseline_accs)-np.array(base_accs))):.2%}",
            f"All {args.refine_tag}: Acc={float(np.mean(refine_accs)):.4f}, Drop={float(np.mean(np.array(baseline_accs)-np.array(refine_accs))):.2%}",
            "",
            _format(summary),
        ]
    )
    (out_dir / "summary.txt").write_text(note + "\n", encoding="utf-8")
    print(note)
    print(f"[Saved] {out_dir}")


if __name__ == "__main__":
    main()
