#!/usr/bin/env bash
set -euo pipefail

# Final full-stack path:
#   SimHash + LRU/CAM + residual gate frontend
#   rejected/miss nodes -> graph-aware dynamic BFP encoder pool
#
# The dynamic pool is generated by running the real LLaMA encoder once with
# block-level BFPA4/BFPA6 decisions inside Linear layers.  The resulting pool is
# registered under cache_data and then consumed by the existing
# residual_precision_depth suite as the miss-node encoder backend.
#
# Examples:
#   DATASETS=cora RUNS=1 FORCE_DYNAMIC=1 bash GraphhopSimhash/scripts/run_dynamic_bfp_fullstack.sh
#   DATASETS="cora pubmed arxiv" bash GraphhopSimhash/scripts/run_dynamic_bfp_fullstack.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OFA_DIR="${OFA_DIR:-$(cd "${REPO_DIR}/.." && pwd)}"
PYTHON_BIN="${PYTHON_BIN:-/home/zhangshangtong/.conda/envs/OFA/bin/python}"

DATASETS=(${DATASETS:-cora})
SEED="${SEED:-42}"
LLM_NAME="${LLM_NAME:-llama2_7b}"

DYNAMIC_THRESHOLD="${DYNAMIC_THRESHOLD:-0.20}"
DYNAMIC_STRESS_SCALE="${DYNAMIC_STRESS_SCALE:-8.0}"
DYNAMIC_BLOCK_SIZE="${DYNAMIC_BLOCK_SIZE:-128}"
DYNAMIC_BASE_MANTISSA="${DYNAMIC_BASE_MANTISSA:-4}"
DYNAMIC_REFINE_MANTISSA="${DYNAMIC_REFINE_MANTISSA:-6}"
DYNAMIC_TAG="${DYNAMIC_TAG:-W4GraphBFPA${DYNAMIC_BASE_MANTISSA}to${DYNAMIC_REFINE_MANTISSA}_B${DYNAMIC_BLOCK_SIZE}_deg_t${DYNAMIC_THRESHOLD}}"

REFERENCE_TAG="${REFERENCE_TAG:-W4BFPA8_B128}"
FORCE_DYNAMIC="${FORCE_DYNAMIC:-0}"
FORCE_FULLSTACK="${FORCE_FULLSTACK:-0}"

# The dynamic pool is consumed as the low-cost miss-node backend.  For
# residual-gate calibration we keep the same visible precision-depth ladder as
# the stable progressive-BFP policy table: BFPA8 reference, BFPA6 refinement,
# and BFPA4-like base.  This avoids changing the front-end accept/reject
# behavior merely because the base backend is dynamic.
FRONTEND_REFINE_BIT="${FRONTEND_REFINE_BIT:-6}"
FRONTEND_REFINE_TAG="${FRONTEND_REFINE_TAG:-W4BFPA${FRONTEND_REFINE_BIT}_B128}"
FRONTEND_REFINE_RATIO="${FRONTEND_REFINE_RATIO:-0.25}"
FRONTEND_BUDGET_PRIORITIES="${FRONTEND_BUDGET_PRIORITIES:-random degree tser}"

cd "${OFA_DIR}"

timestamp() {
  date +"%Y-%m-%d %H:%M:%S"
}

default_runs() {
  case "$1" in
    cora) echo "${RUNS:-3}" ;;
    pubmed) echo "${RUNS:-3}" ;;
    arxiv) echo "${RUNS:-1}" ;;
    *) echo "${RUNS:-1}" ;;
  esac
}

default_frontend_t() {
  case "$1" in
    cora) echo "${THRESHOLD:-31}" ;;
    pubmed) echo "${THRESHOLD:-31}" ;;
    arxiv) echo "${THRESHOLD:-22}" ;;
    *) echo "${THRESHOLD:-31}" ;;
  esac
}

cache_pool_path() {
  local dataset="$1"
  "${PYTHON_BIN}" - <<PY
from GraphhopSimhash.real_quant import default_pool_path
print(default_pool_path("${dataset}", "${LLM_NAME}", "${DYNAMIC_TAG}"))
PY
}

for dataset in "${DATASETS[@]}"; do
  runs="$(default_runs "${dataset}")"
  frontend_t="$(default_frontend_t "${dataset}")"
  pool_path="$(cache_pool_path "${dataset}")"
  meta_path="${pool_path%.pt}.json"

  echo "================================================================"
  echo "[$(timestamp)] Dynamic BFP full-stack | dataset=${dataset}"
  echo "dynamic_tag=${DYNAMIC_TAG}"
  echo "frontend_T=${frontend_t} runs=${runs}"
  echo "pool=${pool_path}"
  echo "================================================================"

  if [[ "${FORCE_DYNAMIC}" == "1" || ! -f "${pool_path}" || ! -f "${meta_path}" ]]; then
    echo "[$(timestamp)] [Pool] generating/registering ${dataset} ${DYNAMIC_TAG}"
    overwrite_args=()
    if [[ "${FORCE_DYNAMIC}" == "1" ]]; then
      overwrite_args=(--overwrite)
    fi
    "${PYTHON_BIN}" GraphhopSimhash/scripts/generate_graph_aware_bfp_dynamic_pool.py \
      --dataset "${dataset}" \
      --llm_name "${LLM_NAME}" \
      --threshold "${DYNAMIC_THRESHOLD}" \
      --stress_scale "${DYNAMIC_STRESS_SCALE}" \
      --block_size "${DYNAMIC_BLOCK_SIZE}" \
      --base_mantissa "${DYNAMIC_BASE_MANTISSA}" \
      --refine_mantissa "${DYNAMIC_REFINE_MANTISSA}" \
      --cache_tag "${DYNAMIC_TAG}" \
      --save_to_cache \
      --runs "${runs}" \
      --seed "${SEED}" \
      "${overwrite_args[@]}"
  else
    echo "[$(timestamp)] [Pool] reuse cached ${pool_path}"
  fi

  effective_bits="$("${PYTHON_BIN}" - <<PY
import json
from pathlib import Path
meta = json.loads(Path("${meta_path}").read_text(encoding="utf-8"))
print(f"{float(meta['effective_bits']):.6f}")
PY
)"
  refined_ratio="$("${PYTHON_BIN}" - <<PY
import json
from pathlib import Path
meta = json.loads(Path("${meta_path}").read_text(encoding="utf-8"))
print(f"{float(meta['refined_ratio']):.6f}")
PY
)"
  has_array_trace="$("${PYTHON_BIN}" - <<PY
import json
from pathlib import Path
meta = json.loads(Path("${meta_path}").read_text(encoding="utf-8"))
print("1" if (meta.get("array_trace") or {}).get("modules") else "0")
PY
)"

  out_dir="${OFA_DIR}/output/dynamic_bfp_fullstack/${dataset}_T${frontend_t}_${DYNAMIC_TAG}_runs${runs}"
  mkdir -p "${out_dir}"
  cat > "${out_dir}/dynamic_bfp_backend_metadata.txt" <<EOF
dataset=${dataset}
frontend_T=${frontend_t}
runs=${runs}
dynamic_tag=${DYNAMIC_TAG}
pool_path=${pool_path}
metadata=${meta_path}
refined_ratio=${refined_ratio}
effective_mantissa_bits=${effective_bits}
note=runner row AllP4 loads this dynamic BFPA4/BFPA6 pool; use effective_mantissa_bits for hardware cost accounting.
EOF

  echo "[$(timestamp)] [FullStack] effective_bits=${effective_bits} refined_ratio=${refined_ratio}"
  if [[ "${has_array_trace}" == "1" ]]; then
    echo "[$(timestamp)] [ArrayTrace] summarizing dynamic BFPA4/BFPA6 array activity"
    "${PYTHON_BIN}" GraphhopSimhash/scripts/simulate_dynamic_bfp_array_trace.py \
      --metadata "${meta_path}" \
      --output_dir "${out_dir}/array_trace"
  else
    echo "[$(timestamp)] [ArrayTrace] metadata has no per-module trace; regenerate the pool with the updated generator to enable array simulation"
  fi

  # PubMed's stable unified-policy point is deliberately conservative at the
  # fuzzy bucket: support>=5 remains direct reuse, while support=3..4 is sent
  # back to the encoder.  Keep this as the default for dynamic-BFP evaluation so
  # the backend is measured after the front-end drop is controlled.
  dataset_gate_threshold="${RESIDUAL_GATE_THRESHOLD:-}"
  if [[ -z "${dataset_gate_threshold}" && "${dataset}" == "pubmed" ]]; then
    dataset_gate_threshold="1.1"
  fi

  FORCE="${FORCE_FULLSTACK}" \
  DATASET="${dataset}" \
  RUNS="${runs}" \
  SEED="${SEED}" \
  THRESHOLD="${frontend_t}" \
  HARD_SUPPORT="${HARD_SUPPORT:-5}" \
  SOFT_SUPPORT="${SOFT_SUPPORT:-3}" \
  REFERENCE_TAG="${REFERENCE_TAG}" \
  RESIDUAL_GATE_THRESHOLD="${dataset_gate_threshold:-${RESIDUAL_GATE_THRESHOLD:-0.575}}" \
  BASE_BIT="${DYNAMIC_BASE_MANTISSA}" \
  BASE_TAG="${DYNAMIC_TAG}" \
  REFINE_BIT="${FRONTEND_REFINE_BIT}" \
  REFINE_TAG="${FRONTEND_REFINE_TAG}" \
  REFINE_RATIO="${FRONTEND_REFINE_RATIO}" \
  BUDGET_PRIORITIES="${BUDGET_PRIORITIES:-${FRONTEND_BUDGET_PRIORITIES}}" \
  FRONTEND_ID="h8_53_T${frontend_t}_dynbfp" \
  OUT_DIR="${out_dir}" \
  bash GraphhopSimhash/scripts/run_progressive_bfp_fullstack.sh

  echo "[$(timestamp)] [Done] ${out_dir}"
done
